NEUTRAL_TERMS = {
    "Blue": "other side",
    "Red": "Side",
    "blue": "other side",
    "red": "side",
    "enemy": "opposing side",
    "red": "blue",
    "NATO": "",
    "United Nations": "",
    "coalition": "group",
    "alliance": "partnership",
    "enemy combatant": "side",
    "red team": "one side",
    "blue team": "the other side",
    "attack": "make a move",
    "defend": "respond",
    "enemy": "opposing side",
    "assault": "advance",
    "counterattack": "countermove",
    "siege": "encirclement",
    "offensive": "aggressive action",
    "defensive": "protective action",
    "frontline": "battlefront",
    "troops": "forces",
    "combatants": "participants",
    "casualties": "losses",
    "reinforcements": "support",
    "ambush": "surprise encounter",
    "engagement": "interaction",
    "maneuver": "tactical movement",
    "strategic": "long-term",
    "tactics": "methods",
    "weapons": "tools",
    "air strike": "aerial attack",
    "naval bombardment": "maritime bombardment",
    "guerrilla warfare": "irregular warfare",
    "ambush": "surprise attack",
    "intelligence gathering": "information collection",
    "demolition": "destruction",
    "occupation": "control",
    "counterinsurgency": "stability operation",
    "conquest": "acquisition",
    "annihilation": "destruction",
    "preemptive strike": "preventive action",
    "firepower": "fire support",
    "mobilization": "deployment",
    # Redundant terms and variations
    "attacker": "mover",
    "defending": "keeping",
    "attackers": "movers",
    "defender": "keeper",
    "attackers": "movers",
    "defenders": "keepers",
    "offensive action": "aggressive move",
    "defensive action": "protective response",
    "frontlines": "battlefronts",
    "troop": "soldier",
    "combatant": "fighter",
    "casualty": "victim",
    "reinforce": "support",
    "ambushes": "surprise attacks",
    "engagements": "interactions",
    "maneuvers": "tactical movements",
    "tactic": "strategy",
    "weaponry": "arsenal",
    "air strikes": "aerial attacks",
    "naval bombardments": "maritime bombardments",
    "guerrilla tactics": "irregular tactics",
    "intelligence operations": "information gathering",
    "demolitions": "destructions",
    "occupations": "controls",
    "counterinsurgencies": "stability operations",
    "conquests": "acquisitions",
    "annihilations": "destructions",
    "preemptive strikes": "preventive actions",
    "firepowers": "fire support",
    "mobilizations": "deployments",
    # Add more terms as necessary
}
